name: Lua CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        apt-get update
        apt-get install -y ninja-build

    - name: Executable
      run: chmod +x ./build.sh

    - name: Build
      run: ./build.sh --native
